# Generated by Django 3.0.4 on 2020-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.ManyToManyField(null=True, to='catalog.DoctorExperience'),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='date_end',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='name_job',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
