# Generated by Django 3.0.4 on 2020-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200305_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoctorExperience',
        ),
    ]
