# Generated by Django 3.0.4 on 2020-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200305_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
